version: "3.5"

services:
  tor:
    image: wizardrysteamworks/tor-snowflake:latest
    container_name: tor
    restart: always
    # Expose only to host's loopback
    ports:
      - "9050:9050"   # Tor SOCKS
      - "9053:9053"   # Tor control (optional)
    volumes:
      - ./tor/etc:/run/tor/config:Z
      - ./tor/data:/run/tor/data:Z

  psiphon:
    image: swarupsengupta2007/psiphon:latest
    container_name: psiphon
    depends_on:
      - tor
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./psiphon:/config:Z
    ports:
      - "1080:1080"   # Psiphon SOCKS
      - "8080:8080"   # Psiphon HTTP
    restart: always

  # Note: Doesn't Work As Tor Socks5 Doesn't Support UDP Protocol.
  # warp:
  #   build: ./warp
  #   container_name: warp
  #   depends_on:
  #     - tor
  #   ports:
  #     - "8086:8086"   # WARP SOCKS5 Proxy
  #   cap_add:
  #     - NET_ADMIN     # Required to create TUN device and manage routing
  #   devices:
  #     - /dev/net/tun  # Required to mount the TUN device
  #   restart: always

  ### Note: UDP VPN Services Such As Wireguard And OpenVPN UDP Can't Be Used Due to Tor Socks5 Lack Of UDP Support; Only TCP VPNs Such As OpenVPN TCP And SSH Will Work. ###